spring:
  profiles:
    active: common
app:
  logging:
    host: 192.168.6.182:5000

---
# Coloque aqui suas configurações de Desenvolvimento
spring:
  profiles:
    active: dev

server:
  port: 9898
---
# Coloque aqui suas configurações de Homologação
spring:
  profiles:
    active: homo

---
spring:
  profiles:
    active: deleteMe, produto, filial
  datasource:
    url: jdbc:mysql://localhost:3306/treinamento_spring
    username: root
    password: ''